channels:
  - mvdbeek
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cmake=3.25.0
  - make=4.3.0
  - nbval=0.9.6
  - ncurses=6.5
  - python=3.10.20
  - pytest
  - pytest-forked
  - pytest-xdist
  - Sphinx==3.3.1
