#include <stdint.h>
#include <stdio.h>

#include <xcore/hwtimer.h>

#include "nn_layers.h"

#define SIZE 16

#ifdef __xcore__
#define WORD_ALIGNED __attribute__((aligned(4)))
#else
#define WORD_ALIGNED
#endif

static uint8_t saturating_double_scalar(uint8_t x) {
  const unsigned y = ((unsigned)x) * 2U;
  return (y > 255U) ? 255U : (uint8_t)y;
}

static void saturating_double_u8(uint8_t *expected, const uint8_t *input, int n) {
  for (int i = 0; i < n; i++) {
    expected[i] = saturating_double_scalar(input[i]);
  }
}

static void print_arr_uint8(const char *name, const uint8_t *v, int n) {
  printf("%s: ", name);
  for (int i = 0; i < n; i++) {
    printf("%u%s", (unsigned)v[i], (i + 1 == n) ? "\n" : ", ");
  }
}

static int count_mismatches_u8(const uint8_t *a, const uint8_t *b, int n) {
  int mismatches = 0;
  for (int i = 0; i < n; i++) {
    if (a[i] != b[i]) mismatches++;
  }
  return mismatches;
}

// Autogenerated: uint8 -> saturating (2 * x).
static const uint8_t double_lut[256] = {
     0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,
    32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,  62,
    64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,  88,  90,  92,  94,
    96,  98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
   128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158,
   160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190,
   192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222,
   224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
   255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
   255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
   255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
   255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
   255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
   255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
   255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
   255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255
};

int main(void) {
  uint8_t input_u8[SIZE] WORD_ALIGNED = {0, 1, 4, 8, 16, 32, 64, 100, 120, 127, 128, 140, 160, 200, 240, 255};
  uint8_t output_u8[SIZE] WORD_ALIGNED = {0};
  uint8_t expected_u8[SIZE] WORD_ALIGNED = {0};
  unsigned start_time, end_time;

  start_time = get_reference_time();
  saturating_double_u8(expected_u8, input_u8, SIZE);
  end_time = get_reference_time();
  printf("ref time: %u\n", end_time - start_time);

  start_time = get_reference_time();
  lookup8(output_u8, input_u8, double_lut, 0, SIZE);
  end_time = get_reference_time();
  printf("lookup8 time: %u\n", end_time - start_time);

  const int mismatches = count_mismatches_u8(output_u8, expected_u8, SIZE);

  print_arr_uint8("Input", input_u8, SIZE);
  print_arr_uint8("Output", output_u8, SIZE);
  print_arr_uint8("Expected", expected_u8, SIZE);
  printf("mismatches=%d\n", mismatches);

  return (mismatches == 0) ? 0 : 1;
}
